# Generated by Django 6.0.6 on 2026-09-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoyaneblog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
