[project]
name = "proyectoyane"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudinary>=1.46.2",
    "crispy-bootstrap5>=2026.3",
    "dj-database-url>=3.1.2",
    "django>=6.0.6",
    "django-anymail>=15.2",
    "django-cloudinary-storage>=0.3.0",
    "django-crispy-forms>=2.7",
    "gunicorn>=26.2.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "ruff>=0.15.20",
    "whitenoise>=6.12.0",
]
