# Generated by Django 6.0.6 on 2026-08-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoyaneapp', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
