# Generated by Django 6.0.6 on 2026-08-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoyaneapp', '0004_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
