# Generated by Django 6.0.6 on 2026-08-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoyaneshop', '0002_product_is_active_product_price_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
