# Generated by Django 6.0.6 on 2026-09-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoyaneshop', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
